### ISSUE TITLE
Problem in docs build with docutils==0.17

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1625]
We have docs builds failing at the moment, e.g. [here](https://github.com/tskit-dev/msprime/pull/1616/checks?check_run_id=2277465063#step:10:12)

Backtrace:
```
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/docutils/parsers/rst/__init__.py", line 196, in parse
53
    if len(line) > self.document.settings.line_length_limit:
54
AttributeError: 'Values' object has no attribute 'line_length_limit'
55
The full traceback has been saved in /tmp/sphinx-err-1nj6ookf.log, if you want to report the issue to the developers.
56
Please also report this if it was a user error, so that a better error message can be provided next time.
57
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
58
Traceback (most recent call last):
59
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/jupyter_book/sphinx.py", line 150, in build_sphinx
60
    app.build(force_all, filenames)
61
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/sphinx/application.py", line 352, in build
62
    self.builder.build_update()
63
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 297, in build_update
64
    self.build(to_build,
65
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 311, in build
66
    updated_docnames = set(self.read())
67
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 418, in read
68
    self._read_serial(docnames)
69
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
70
    self.read_doc(docname)
71
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
72
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
73
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/sphinx/io.py", line 223, in read_doc
74
    pub.publish()
75
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/docutils/core.py", line 217, in publish
76
    self.document = self.reader.read(self.source, self.parser,
77
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/sphinx/io.py", line 128, in read
78
    self.parse()
79
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/docutils/readers/__init__.py", line 78, in parse
80
    self.parser.parse(self.input, document)
81
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/myst_nb/parser.py", line 95, in parse
82
    tokens_to_docutils(md_parser, env, tokens, document)
83
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/myst_nb/parser.py", line 222, in tokens_to_docutils
84
    md.renderer.render(tokens, md.options, env)
85
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/myst_parser/docutils_renderer.py", line 174, in render
86
    self.rules[f"render_{nest_token.type}"](nest_token)
87
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/myst_parser/docutils_renderer.py", line 438, in render_fence
88
    MockRSTParser().parse(pseudosource, newdoc)
89
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/myst_parser/mocking.py", line 493, in parse
90
    super().parse(inputstring, document)
91
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/docutils/parsers/rst/__init__.py", line 196, in parse
92
    if len(line) > self.document.settings.line_length_limit:
93
AttributeError: 'Values' object has no attribute 'line_length_limit'
94

95
The above exception was the direct cause of the following exception:
96

97
Traceback (most recent call last):
98
  File "/opt/hostedtoolcache/Python/3.8.8/x64/bin/jupyter-book", line 8, in <module>
99
    sys.exit(main())
100
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/click/core.py", line 829, in __call__
101
    return self.main(*args, **kwargs)
102
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/click/core.py", line 782, in main
103
    rv = self.invoke(ctx)
104
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
105
    return _process_result(sub_ctx.command.invoke(sub_ctx))
106
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
107
    return ctx.invoke(self.callback, **ctx.params)
108
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/click/core.py", line 610, in invoke
109
    return callback(*args, **kwargs)
110
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/jupyter_book/commands/__init__.py", line 304, in build
111
    builder_specific_actions(
112
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/jupyter_book/commands/__init__.py", line 546, in builder_specific_actions
113
    raise RuntimeError(_message_box(msg, color="red", doprint=False)) from result
114
RuntimeError: 
115
===============================================================================
116

117
There was an error in building your book. Look above for the cause.
118

119
===============================================================================
120
```

**Comment by jeromekelleher** [comment]
@benjeffery, @grahamgower, a heads-up on this one. I think it's likely to pop up in other repos with similar toolchains to msprime. I'm not sure whether the issue is in docutils, sphinx or jupyterbook, but one to keep an eye on anyway.

**Comment by grahamgower** [comment]
Yep, I saw this in the demes repo. `jupyter-book` has "fixed" this with a point release to depend explicitly on docutils 0.16.

**Comment by jeromekelleher** [comment]
Have you got a link to the upstream issue please @grahamgower?

**Comment by grahamgower** [comment]
There isn't find much info, I'm afraid. https://github.com/executablebooks/jupyter-book/pull/1289
